// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_MorphingDialog.cpp"
#include "EWIEGA46WW/moc_PhongLighting.cpp"
#include "EWIEGA46WW/moc_PhongLightingWidget.cpp"
#include "EWIEGA46WW/moc_RenderDialog.cpp"
